name: professionAI
channels:
  - defaults
dependencies:
  - _r-mutex=1.0.0=anacondar_1
  - argon2-cffi=20.1.0=py38h2bbff1b_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.2=py38h2a96729_1
  - brotlipy=0.7.0=py38h2bbff1b_1003
  - ca-certificates=2022.4.26=haa95532_0
  - certifi=2022.5.18.1=py38haa95532_0
  - cffi=1.15.0=py38h2bbff1b_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py38haa95532_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cryptography=36.0.0=py38h21b164f_0
  - cymem=2.0.5=py38hd77b12b_0
  - cython=0.29.28=py38hd77b12b_0
  - cython-blis=0.7.4=py38h2bbff1b_1
  - debugpy=1.5.1=py38hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py38_0
  - gensim=4.1.2=py38hd77b12b_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - idna=3.3=pyhd3eb1b0_0
  - importlib-metadata=4.8.2=py38haa95532_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - intel-openmp=2021.4.0=haa95532_3556
  - ipykernel=6.4.1=py38haa95532_1
  - ipython=7.31.1=py38haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.0=py38haa95532_1
  - jinja2=3.0.2=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h2bbff1b_0
  - jsonschema=3.0.2=py38_0
  - jupyter_client=7.1.2=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py38haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - libopencv=4.0.1=hbb9e17c_0
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.2.0=he0120a3_1
  - lz4-c=1.9.3=h2bbff1b_1
  - m2w64-bwidget=1.9.10=2
  - m2w64-bzip2=1.0.6=6
  - m2w64-expat=2.1.1=2
  - m2w64-fftw=3.3.4=6
  - m2w64-flac=1.3.1=3
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-gsl=2.1=2
  - m2w64-libiconv=1.14=6
  - m2w64-libjpeg-turbo=1.4.2=3
  - m2w64-libogg=1.3.2=3
  - m2w64-libpng=1.6.21=2
  - m2w64-libsndfile=1.0.26=2
  - m2w64-libtiff=4.0.6=2
  - m2w64-libvorbis=1.3.5=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-libxml2=2.9.3=4
  - m2w64-mpfr=3.1.4=4
  - m2w64-openblas=0.2.19=1
  - m2w64-pcre=8.38=2
  - m2w64-speex=1.2rc2=3
  - m2w64-speexdsp=1.2rc3=3
  - m2w64-tcl=8.6.5=3
  - m2w64-tk=8.6.5=3
  - m2w64-tktable=2.10=5
  - m2w64-wineditline=2.101=5
  - m2w64-xz=5.2.2=2
  - m2w64-zlib=1.2.8=10
  - markupsafe=2.0.1=py38h2bbff1b_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py38he774522_1000
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py38h2bbff1b_0
  - mkl_fft=1.3.1=py38h277e83a_0
  - mkl_random=1.2.2=py38hf11a4ad_0
  - msys2-conda-epoch=20160418=1
  - murmurhash=1.0.5=py38hd77b12b_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py38haa95532_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - nltk=3.7=pyhd3eb1b0_0
  - notebook=6.4.6=py38haa95532_0
  - numexpr=2.8.1=py38hb80d3ca_0
  - numpy=1.22.3=py38h7a0a035_0
  - numpy-base=1.22.3=py38hca35cd5_0
  - opencv=4.0.1=py38h2a7c758_0
  - openssl=1.1.1o=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.1=py38hd77b12b_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.2=py38haa95532_0
  - plac=1.1.0=py38_1
  - preshed=3.0.5=py38h6c2663c_4
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - py-opencv=4.0.1=py38he44ac1e_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyrsistent=0.18.0=py38h196d8e1_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.12=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2021.3=pyhd3eb1b0_0
  - pywin32=302=py38h827c3e9_1
  - pywinpty=0.5.7=py38_0
  - pyzmq=22.3.0=py38hd77b12b_2
  - r-base=3.6.1=hf18239d_1
  - r-ngram=3.0.4=r36hda5aaf8_0
  - regex=2021.8.3=py38h2bbff1b_0
  - requests=2.27.1=pyhd3eb1b0_0
  - scikit-learn=1.0.2=py38hf11a4ad_1
  - scipy=1.7.3=py38h0a974cb_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py38haa95532_0
  - six=1.16.0=pyhd3eb1b0_0
  - smart_open=5.2.1=py38haa95532_0
  - sqlite=3.37.0=h2bbff1b_0
  - terminado=0.9.4=py38haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tornado=6.1=py38h2bbff1b_0
  - tqdm=4.62.3=pyhd3eb1b0_1
  - traitlets=5.1.1=pyhd3eb1b0_0
  - urllib3=1.26.8=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - wincertstore=0.2=py38haa95532_2
  - winpty=0.4.3=4
  - xz=5.2.5=h8cc25b3_1
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.12=h8cc25b3_2
  - zstd=1.5.2=h19a0ad4_0
  - pip:
    - catalogue==2.0.7
    - en-core-web-sm==3.3.0
    - ipynb==0.5.1
    - langcodes==3.3.0
    - ngram==4.0.3
    - pathy==0.6.1
    - pydantic==1.8.2
    - spacy==3.3.0
    - spacy-legacy==3.0.9
    - spacy-loggers==1.0.2
    - srsly==2.4.3
    - textblob==0.15.3
    - thinc==8.0.16
    - typer==0.4.1
    - typing-extensions==4.2.0
    - wasabi==0.9.1
